version: '3'
services:
  tezos-node:
    hostname: node
    image: tezos/tezos:v13.0
    restart: always
    entrypoint: [ "/bin/sh", "/mnt/node-start.sh" ]
    ports:
      - "9732:9732"
      - "8732:8732"
    volumes:
      - ./scripts:/mnt
      - ${NODE_STORAGE_PATH}/.tezos-node:/home/tezos/.tezos-node
    environment:
      - NET_ADDR=0.0.0.0
      - P2P_PORT=9732
      - RPC_PORT=8732
      - USE_SNAPSHOT=false
      - TEZOS_HOME_CONFIG=/home/tezos/.tezos-node
      - ID_FILE=/home/tezos/.tezos-node/identity.json
      - FILE=/mnt/snapshot.rolling
      - USE_SNAPSHOT=${USE_SNAPSHOT}
  tezos-signer:
    hostname: signer
    image: tezos/tezos:v13.0
    restart: always
    volumes:
      - ./scripts:/mnt
    depends_on:
      - tezos-node
    entrypoint: [ "/bin/sh", "/mnt/signer-start.sh" ]
    environment:
      - SIGNER_PORT=7000
      - BAKER_SECRET_KEY=${BAKER_SECRET_KEY}
  tezos-baker:
    hostname: baker
    image: tezos/tezos:v13.0
    entrypoint: [ "/bin/sh", "/mnt/baker-start.sh" ]
    volumes:
      - ./scripts:/mnt
      - ${NODE_STORAGE_PATH}/.tezos-node:/home/tezos/.tezos-node
      - ${NODE_STORAGE_PATH}/.tezos-client:/home/tezos/.tezos-client
    restart: on-failure
    environment:
      - PKH=${BAKER_PUB_KEY_HASH}
      - SIGNER_URL=signer:7000
      - NODE_URL=node:8732
    depends_on:
      - tezos-node
      - tezos-signer
  tezos-accuser:
    hostname: accuser
    image: tezos/tezos:v13.0
    entrypoint: [ "/bin/sh", "/mnt/accuser-start.sh" ]
    volumes:
      - ./scripts:/mnt
    restart: always
    environment:
      - PKH=${BAKER_PUB_KEY_HASH}
      - SIGNER_URL=signer:7000
      - NODE_URL=node:8732
    depends_on:
      - tezos-node
      - tezos-signer
  pyrometer:
    hostname: pyrometer
    image: registry.gitlab.com/tezos-kiln/pyrometer
    restart: always
    volumes:
      - ./pyrometer.toml:/home/node/.config/pyrometer/pyrometer.toml
    command: run
    ports:
      - "20000:2020"
